module vec_rev_mod
public
integer, parameter :: vlen = 333 
contains

attributes(global) subroutine vec_rev_gpu(v1,v2)
implicit none
  integer, intent(in), device, dimension(vlen) :: v1
  integer, intent(out), device, dimension(vlen) :: v2

  ! insert kernel body here

end subroutine vec_rev_gpu

integer function max_diff(v1, v2)
implicit none
   integer, intent(in), dimension(:) :: v1, v2

   max_diff = maxval(abs(v1(:) - v2(:)))
end function max_diff


end module vec_rev_mod
